#include <stdio.h>
#include "wren.h"

void wrengoWriteFn(WrenVM* vm, const char* text) {
    printf("%s", text);
}

void wrengoErrorFn(WrenVM* vm, WrenErrorType type, const char* module, int line, const char* message) {
    switch (type) {
        case WREN_ERROR_COMPILE:
            fprintf(stderr, "[%s line %d] [Error] %s\n", module, line, message);
            break;
        case WREN_ERROR_STACK_TRACE:
            fprintf(stderr, "[%s line %d] in %s\n", module, line, message);
            break;
        case WREN_ERROR_RUNTIME:
            fprintf(stderr, "[Runtime Error] %s\n", message);
            break;
    }
}


// Foreign method wrapper functions
// These call back to Go with their specific wrapper ID
extern void goForeignMethodCallback(WrenVM* vm, int wrapperId);

void wrengoForeignMethod_0(WrenVM* vm) { goForeignMethodCallback(vm, 0); }
void wrengoForeignMethod_1(WrenVM* vm) { goForeignMethodCallback(vm, 1); }
void wrengoForeignMethod_2(WrenVM* vm) { goForeignMethodCallback(vm, 2); }
void wrengoForeignMethod_3(WrenVM* vm) { goForeignMethodCallback(vm, 3); }
void wrengoForeignMethod_4(WrenVM* vm) { goForeignMethodCallback(vm, 4); }
void wrengoForeignMethod_5(WrenVM* vm) { goForeignMethodCallback(vm, 5); }
void wrengoForeignMethod_6(WrenVM* vm) { goForeignMethodCallback(vm, 6); }
void wrengoForeignMethod_7(WrenVM* vm) { goForeignMethodCallback(vm, 7); }
void wrengoForeignMethod_8(WrenVM* vm) { goForeignMethodCallback(vm, 8); }
void wrengoForeignMethod_9(WrenVM* vm) { goForeignMethodCallback(vm, 9); }
void wrengoForeignMethod_10(WrenVM* vm) { goForeignMethodCallback(vm, 10); }
void wrengoForeignMethod_11(WrenVM* vm) { goForeignMethodCallback(vm, 11); }
void wrengoForeignMethod_12(WrenVM* vm) { goForeignMethodCallback(vm, 12); }
void wrengoForeignMethod_13(WrenVM* vm) { goForeignMethodCallback(vm, 13); }
void wrengoForeignMethod_14(WrenVM* vm) { goForeignMethodCallback(vm, 14); }
void wrengoForeignMethod_15(WrenVM* vm) { goForeignMethodCallback(vm, 15); }
void wrengoForeignMethod_16(WrenVM* vm) { goForeignMethodCallback(vm, 16); }
void wrengoForeignMethod_17(WrenVM* vm) { goForeignMethodCallback(vm, 17); }
void wrengoForeignMethod_18(WrenVM* vm) { goForeignMethodCallback(vm, 18); }
void wrengoForeignMethod_19(WrenVM* vm) { goForeignMethodCallback(vm, 19); }
void wrengoForeignMethod_20(WrenVM* vm) { goForeignMethodCallback(vm, 20); }
void wrengoForeignMethod_21(WrenVM* vm) { goForeignMethodCallback(vm, 21); }
void wrengoForeignMethod_22(WrenVM* vm) { goForeignMethodCallback(vm, 22); }
void wrengoForeignMethod_23(WrenVM* vm) { goForeignMethodCallback(vm, 23); }
void wrengoForeignMethod_24(WrenVM* vm) { goForeignMethodCallback(vm, 24); }
void wrengoForeignMethod_25(WrenVM* vm) { goForeignMethodCallback(vm, 25); }
void wrengoForeignMethod_26(WrenVM* vm) { goForeignMethodCallback(vm, 26); }
void wrengoForeignMethod_27(WrenVM* vm) { goForeignMethodCallback(vm, 27); }
void wrengoForeignMethod_28(WrenVM* vm) { goForeignMethodCallback(vm, 28); }
void wrengoForeignMethod_29(WrenVM* vm) { goForeignMethodCallback(vm, 29); }
void wrengoForeignMethod_30(WrenVM* vm) { goForeignMethodCallback(vm, 30); }
void wrengoForeignMethod_31(WrenVM* vm) { goForeignMethodCallback(vm, 31); }
void wrengoForeignMethod_32(WrenVM* vm) { goForeignMethodCallback(vm, 32); }
void wrengoForeignMethod_33(WrenVM* vm) { goForeignMethodCallback(vm, 33); }
void wrengoForeignMethod_34(WrenVM* vm) { goForeignMethodCallback(vm, 34); }
void wrengoForeignMethod_35(WrenVM* vm) { goForeignMethodCallback(vm, 35); }
void wrengoForeignMethod_36(WrenVM* vm) { goForeignMethodCallback(vm, 36); }
void wrengoForeignMethod_37(WrenVM* vm) { goForeignMethodCallback(vm, 37); }
void wrengoForeignMethod_38(WrenVM* vm) { goForeignMethodCallback(vm, 38); }
void wrengoForeignMethod_39(WrenVM* vm) { goForeignMethodCallback(vm, 39); }
void wrengoForeignMethod_40(WrenVM* vm) { goForeignMethodCallback(vm, 40); }
void wrengoForeignMethod_41(WrenVM* vm) { goForeignMethodCallback(vm, 41); }
void wrengoForeignMethod_42(WrenVM* vm) { goForeignMethodCallback(vm, 42); }
void wrengoForeignMethod_43(WrenVM* vm) { goForeignMethodCallback(vm, 43); }
void wrengoForeignMethod_44(WrenVM* vm) { goForeignMethodCallback(vm, 44); }
void wrengoForeignMethod_45(WrenVM* vm) { goForeignMethodCallback(vm, 45); }
void wrengoForeignMethod_46(WrenVM* vm) { goForeignMethodCallback(vm, 46); }
void wrengoForeignMethod_47(WrenVM* vm) { goForeignMethodCallback(vm, 47); }
void wrengoForeignMethod_48(WrenVM* vm) { goForeignMethodCallback(vm, 48); }
void wrengoForeignMethod_49(WrenVM* vm) { goForeignMethodCallback(vm, 49); }
void wrengoForeignMethod_50(WrenVM* vm) { goForeignMethodCallback(vm, 50); }
void wrengoForeignMethod_51(WrenVM* vm) { goForeignMethodCallback(vm, 51); }
void wrengoForeignMethod_52(WrenVM* vm) { goForeignMethodCallback(vm, 52); }
void wrengoForeignMethod_53(WrenVM* vm) { goForeignMethodCallback(vm, 53); }
void wrengoForeignMethod_54(WrenVM* vm) { goForeignMethodCallback(vm, 54); }
void wrengoForeignMethod_55(WrenVM* vm) { goForeignMethodCallback(vm, 55); }
void wrengoForeignMethod_56(WrenVM* vm) { goForeignMethodCallback(vm, 56); }
void wrengoForeignMethod_57(WrenVM* vm) { goForeignMethodCallback(vm, 57); }
void wrengoForeignMethod_58(WrenVM* vm) { goForeignMethodCallback(vm, 58); }
void wrengoForeignMethod_59(WrenVM* vm) { goForeignMethodCallback(vm, 59); }
void wrengoForeignMethod_60(WrenVM* vm) { goForeignMethodCallback(vm, 60); }
void wrengoForeignMethod_61(WrenVM* vm) { goForeignMethodCallback(vm, 61); }
void wrengoForeignMethod_62(WrenVM* vm) { goForeignMethodCallback(vm, 62); }
void wrengoForeignMethod_63(WrenVM* vm) { goForeignMethodCallback(vm, 63); }
void wrengoForeignMethod_64(WrenVM* vm) { goForeignMethodCallback(vm, 64); }
void wrengoForeignMethod_65(WrenVM* vm) { goForeignMethodCallback(vm, 65); }
void wrengoForeignMethod_66(WrenVM* vm) { goForeignMethodCallback(vm, 66); }
void wrengoForeignMethod_67(WrenVM* vm) { goForeignMethodCallback(vm, 67); }
void wrengoForeignMethod_68(WrenVM* vm) { goForeignMethodCallback(vm, 68); }
void wrengoForeignMethod_69(WrenVM* vm) { goForeignMethodCallback(vm, 69); }
void wrengoForeignMethod_70(WrenVM* vm) { goForeignMethodCallback(vm, 70); }
void wrengoForeignMethod_71(WrenVM* vm) { goForeignMethodCallback(vm, 71); }
void wrengoForeignMethod_72(WrenVM* vm) { goForeignMethodCallback(vm, 72); }
void wrengoForeignMethod_73(WrenVM* vm) { goForeignMethodCallback(vm, 73); }
void wrengoForeignMethod_74(WrenVM* vm) { goForeignMethodCallback(vm, 74); }
void wrengoForeignMethod_75(WrenVM* vm) { goForeignMethodCallback(vm, 75); }
void wrengoForeignMethod_76(WrenVM* vm) { goForeignMethodCallback(vm, 76); }
void wrengoForeignMethod_77(WrenVM* vm) { goForeignMethodCallback(vm, 77); }
void wrengoForeignMethod_78(WrenVM* vm) { goForeignMethodCallback(vm, 78); }
void wrengoForeignMethod_79(WrenVM* vm) { goForeignMethodCallback(vm, 79); }
void wrengoForeignMethod_80(WrenVM* vm) { goForeignMethodCallback(vm, 80); }
void wrengoForeignMethod_81(WrenVM* vm) { goForeignMethodCallback(vm, 81); }
void wrengoForeignMethod_82(WrenVM* vm) { goForeignMethodCallback(vm, 82); }
void wrengoForeignMethod_83(WrenVM* vm) { goForeignMethodCallback(vm, 83); }
void wrengoForeignMethod_84(WrenVM* vm) { goForeignMethodCallback(vm, 84); }
void wrengoForeignMethod_85(WrenVM* vm) { goForeignMethodCallback(vm, 85); }
void wrengoForeignMethod_86(WrenVM* vm) { goForeignMethodCallback(vm, 86); }
void wrengoForeignMethod_87(WrenVM* vm) { goForeignMethodCallback(vm, 87); }
void wrengoForeignMethod_88(WrenVM* vm) { goForeignMethodCallback(vm, 88); }
void wrengoForeignMethod_89(WrenVM* vm) { goForeignMethodCallback(vm, 89); }
void wrengoForeignMethod_90(WrenVM* vm) { goForeignMethodCallback(vm, 90); }
void wrengoForeignMethod_91(WrenVM* vm) { goForeignMethodCallback(vm, 91); }
void wrengoForeignMethod_92(WrenVM* vm) { goForeignMethodCallback(vm, 92); }
void wrengoForeignMethod_93(WrenVM* vm) { goForeignMethodCallback(vm, 93); }
void wrengoForeignMethod_94(WrenVM* vm) { goForeignMethodCallback(vm, 94); }
void wrengoForeignMethod_95(WrenVM* vm) { goForeignMethodCallback(vm, 95); }
void wrengoForeignMethod_96(WrenVM* vm) { goForeignMethodCallback(vm, 96); }
void wrengoForeignMethod_97(WrenVM* vm) { goForeignMethodCallback(vm, 97); }
void wrengoForeignMethod_98(WrenVM* vm) { goForeignMethodCallback(vm, 98); }

// Additional wrappers 99-299
void wrengoForeignMethod_99(WrenVM* vm) { goForeignMethodCallback(vm, 99); }
void wrengoForeignMethod_100(WrenVM* vm) { goForeignMethodCallback(vm, 100); }
void wrengoForeignMethod_101(WrenVM* vm) { goForeignMethodCallback(vm, 101); }
void wrengoForeignMethod_102(WrenVM* vm) { goForeignMethodCallback(vm, 102); }
void wrengoForeignMethod_103(WrenVM* vm) { goForeignMethodCallback(vm, 103); }
void wrengoForeignMethod_104(WrenVM* vm) { goForeignMethodCallback(vm, 104); }
void wrengoForeignMethod_105(WrenVM* vm) { goForeignMethodCallback(vm, 105); }
void wrengoForeignMethod_106(WrenVM* vm) { goForeignMethodCallback(vm, 106); }
void wrengoForeignMethod_107(WrenVM* vm) { goForeignMethodCallback(vm, 107); }
void wrengoForeignMethod_108(WrenVM* vm) { goForeignMethodCallback(vm, 108); }
void wrengoForeignMethod_109(WrenVM* vm) { goForeignMethodCallback(vm, 109); }
void wrengoForeignMethod_110(WrenVM* vm) { goForeignMethodCallback(vm, 110); }
void wrengoForeignMethod_111(WrenVM* vm) { goForeignMethodCallback(vm, 111); }
void wrengoForeignMethod_112(WrenVM* vm) { goForeignMethodCallback(vm, 112); }
void wrengoForeignMethod_113(WrenVM* vm) { goForeignMethodCallback(vm, 113); }
void wrengoForeignMethod_114(WrenVM* vm) { goForeignMethodCallback(vm, 114); }
void wrengoForeignMethod_115(WrenVM* vm) { goForeignMethodCallback(vm, 115); }
void wrengoForeignMethod_116(WrenVM* vm) { goForeignMethodCallback(vm, 116); }
void wrengoForeignMethod_117(WrenVM* vm) { goForeignMethodCallback(vm, 117); }
void wrengoForeignMethod_118(WrenVM* vm) { goForeignMethodCallback(vm, 118); }
void wrengoForeignMethod_119(WrenVM* vm) { goForeignMethodCallback(vm, 119); }
void wrengoForeignMethod_120(WrenVM* vm) { goForeignMethodCallback(vm, 120); }
void wrengoForeignMethod_121(WrenVM* vm) { goForeignMethodCallback(vm, 121); }
void wrengoForeignMethod_122(WrenVM* vm) { goForeignMethodCallback(vm, 122); }
void wrengoForeignMethod_123(WrenVM* vm) { goForeignMethodCallback(vm, 123); }
void wrengoForeignMethod_124(WrenVM* vm) { goForeignMethodCallback(vm, 124); }
void wrengoForeignMethod_125(WrenVM* vm) { goForeignMethodCallback(vm, 125); }
void wrengoForeignMethod_126(WrenVM* vm) { goForeignMethodCallback(vm, 126); }
void wrengoForeignMethod_127(WrenVM* vm) { goForeignMethodCallback(vm, 127); }
void wrengoForeignMethod_128(WrenVM* vm) { goForeignMethodCallback(vm, 128); }
void wrengoForeignMethod_129(WrenVM* vm) { goForeignMethodCallback(vm, 129); }
void wrengoForeignMethod_130(WrenVM* vm) { goForeignMethodCallback(vm, 130); }
void wrengoForeignMethod_131(WrenVM* vm) { goForeignMethodCallback(vm, 131); }
void wrengoForeignMethod_132(WrenVM* vm) { goForeignMethodCallback(vm, 132); }
void wrengoForeignMethod_133(WrenVM* vm) { goForeignMethodCallback(vm, 133); }
void wrengoForeignMethod_134(WrenVM* vm) { goForeignMethodCallback(vm, 134); }
void wrengoForeignMethod_135(WrenVM* vm) { goForeignMethodCallback(vm, 135); }
void wrengoForeignMethod_136(WrenVM* vm) { goForeignMethodCallback(vm, 136); }
void wrengoForeignMethod_137(WrenVM* vm) { goForeignMethodCallback(vm, 137); }
void wrengoForeignMethod_138(WrenVM* vm) { goForeignMethodCallback(vm, 138); }
void wrengoForeignMethod_139(WrenVM* vm) { goForeignMethodCallback(vm, 139); }
void wrengoForeignMethod_140(WrenVM* vm) { goForeignMethodCallback(vm, 140); }
void wrengoForeignMethod_141(WrenVM* vm) { goForeignMethodCallback(vm, 141); }
void wrengoForeignMethod_142(WrenVM* vm) { goForeignMethodCallback(vm, 142); }
void wrengoForeignMethod_143(WrenVM* vm) { goForeignMethodCallback(vm, 143); }
void wrengoForeignMethod_144(WrenVM* vm) { goForeignMethodCallback(vm, 144); }
void wrengoForeignMethod_145(WrenVM* vm) { goForeignMethodCallback(vm, 145); }
void wrengoForeignMethod_146(WrenVM* vm) { goForeignMethodCallback(vm, 146); }
void wrengoForeignMethod_147(WrenVM* vm) { goForeignMethodCallback(vm, 147); }
void wrengoForeignMethod_148(WrenVM* vm) { goForeignMethodCallback(vm, 148); }
void wrengoForeignMethod_149(WrenVM* vm) { goForeignMethodCallback(vm, 149); }
void wrengoForeignMethod_150(WrenVM* vm) { goForeignMethodCallback(vm, 150); }
void wrengoForeignMethod_151(WrenVM* vm) { goForeignMethodCallback(vm, 151); }
void wrengoForeignMethod_152(WrenVM* vm) { goForeignMethodCallback(vm, 152); }
void wrengoForeignMethod_153(WrenVM* vm) { goForeignMethodCallback(vm, 153); }
void wrengoForeignMethod_154(WrenVM* vm) { goForeignMethodCallback(vm, 154); }
void wrengoForeignMethod_155(WrenVM* vm) { goForeignMethodCallback(vm, 155); }
void wrengoForeignMethod_156(WrenVM* vm) { goForeignMethodCallback(vm, 156); }
void wrengoForeignMethod_157(WrenVM* vm) { goForeignMethodCallback(vm, 157); }
void wrengoForeignMethod_158(WrenVM* vm) { goForeignMethodCallback(vm, 158); }
void wrengoForeignMethod_159(WrenVM* vm) { goForeignMethodCallback(vm, 159); }
void wrengoForeignMethod_160(WrenVM* vm) { goForeignMethodCallback(vm, 160); }
void wrengoForeignMethod_161(WrenVM* vm) { goForeignMethodCallback(vm, 161); }
void wrengoForeignMethod_162(WrenVM* vm) { goForeignMethodCallback(vm, 162); }
void wrengoForeignMethod_163(WrenVM* vm) { goForeignMethodCallback(vm, 163); }
void wrengoForeignMethod_164(WrenVM* vm) { goForeignMethodCallback(vm, 164); }
void wrengoForeignMethod_165(WrenVM* vm) { goForeignMethodCallback(vm, 165); }
void wrengoForeignMethod_166(WrenVM* vm) { goForeignMethodCallback(vm, 166); }
void wrengoForeignMethod_167(WrenVM* vm) { goForeignMethodCallback(vm, 167); }
void wrengoForeignMethod_168(WrenVM* vm) { goForeignMethodCallback(vm, 168); }
void wrengoForeignMethod_169(WrenVM* vm) { goForeignMethodCallback(vm, 169); }
void wrengoForeignMethod_170(WrenVM* vm) { goForeignMethodCallback(vm, 170); }
void wrengoForeignMethod_171(WrenVM* vm) { goForeignMethodCallback(vm, 171); }
void wrengoForeignMethod_172(WrenVM* vm) { goForeignMethodCallback(vm, 172); }
void wrengoForeignMethod_173(WrenVM* vm) { goForeignMethodCallback(vm, 173); }
void wrengoForeignMethod_174(WrenVM* vm) { goForeignMethodCallback(vm, 174); }
void wrengoForeignMethod_175(WrenVM* vm) { goForeignMethodCallback(vm, 175); }
void wrengoForeignMethod_176(WrenVM* vm) { goForeignMethodCallback(vm, 176); }
void wrengoForeignMethod_177(WrenVM* vm) { goForeignMethodCallback(vm, 177); }
void wrengoForeignMethod_178(WrenVM* vm) { goForeignMethodCallback(vm, 178); }
void wrengoForeignMethod_179(WrenVM* vm) { goForeignMethodCallback(vm, 179); }
void wrengoForeignMethod_180(WrenVM* vm) { goForeignMethodCallback(vm, 180); }
void wrengoForeignMethod_181(WrenVM* vm) { goForeignMethodCallback(vm, 181); }
void wrengoForeignMethod_182(WrenVM* vm) { goForeignMethodCallback(vm, 182); }
void wrengoForeignMethod_183(WrenVM* vm) { goForeignMethodCallback(vm, 183); }
void wrengoForeignMethod_184(WrenVM* vm) { goForeignMethodCallback(vm, 184); }
void wrengoForeignMethod_185(WrenVM* vm) { goForeignMethodCallback(vm, 185); }
void wrengoForeignMethod_186(WrenVM* vm) { goForeignMethodCallback(vm, 186); }
void wrengoForeignMethod_187(WrenVM* vm) { goForeignMethodCallback(vm, 187); }
void wrengoForeignMethod_188(WrenVM* vm) { goForeignMethodCallback(vm, 188); }
void wrengoForeignMethod_189(WrenVM* vm) { goForeignMethodCallback(vm, 189); }
void wrengoForeignMethod_190(WrenVM* vm) { goForeignMethodCallback(vm, 190); }
void wrengoForeignMethod_191(WrenVM* vm) { goForeignMethodCallback(vm, 191); }
void wrengoForeignMethod_192(WrenVM* vm) { goForeignMethodCallback(vm, 192); }
void wrengoForeignMethod_193(WrenVM* vm) { goForeignMethodCallback(vm, 193); }
void wrengoForeignMethod_194(WrenVM* vm) { goForeignMethodCallback(vm, 194); }
void wrengoForeignMethod_195(WrenVM* vm) { goForeignMethodCallback(vm, 195); }
void wrengoForeignMethod_196(WrenVM* vm) { goForeignMethodCallback(vm, 196); }
void wrengoForeignMethod_197(WrenVM* vm) { goForeignMethodCallback(vm, 197); }
void wrengoForeignMethod_198(WrenVM* vm) { goForeignMethodCallback(vm, 198); }
void wrengoForeignMethod_199(WrenVM* vm) { goForeignMethodCallback(vm, 199); }
void wrengoForeignMethod_200(WrenVM* vm) { goForeignMethodCallback(vm, 200); }
void wrengoForeignMethod_201(WrenVM* vm) { goForeignMethodCallback(vm, 201); }
void wrengoForeignMethod_202(WrenVM* vm) { goForeignMethodCallback(vm, 202); }
void wrengoForeignMethod_203(WrenVM* vm) { goForeignMethodCallback(vm, 203); }
void wrengoForeignMethod_204(WrenVM* vm) { goForeignMethodCallback(vm, 204); }
void wrengoForeignMethod_205(WrenVM* vm) { goForeignMethodCallback(vm, 205); }
void wrengoForeignMethod_206(WrenVM* vm) { goForeignMethodCallback(vm, 206); }
void wrengoForeignMethod_207(WrenVM* vm) { goForeignMethodCallback(vm, 207); }
void wrengoForeignMethod_208(WrenVM* vm) { goForeignMethodCallback(vm, 208); }
void wrengoForeignMethod_209(WrenVM* vm) { goForeignMethodCallback(vm, 209); }
void wrengoForeignMethod_210(WrenVM* vm) { goForeignMethodCallback(vm, 210); }
void wrengoForeignMethod_211(WrenVM* vm) { goForeignMethodCallback(vm, 211); }
void wrengoForeignMethod_212(WrenVM* vm) { goForeignMethodCallback(vm, 212); }
void wrengoForeignMethod_213(WrenVM* vm) { goForeignMethodCallback(vm, 213); }
void wrengoForeignMethod_214(WrenVM* vm) { goForeignMethodCallback(vm, 214); }
void wrengoForeignMethod_215(WrenVM* vm) { goForeignMethodCallback(vm, 215); }
void wrengoForeignMethod_216(WrenVM* vm) { goForeignMethodCallback(vm, 216); }
void wrengoForeignMethod_217(WrenVM* vm) { goForeignMethodCallback(vm, 217); }
void wrengoForeignMethod_218(WrenVM* vm) { goForeignMethodCallback(vm, 218); }
void wrengoForeignMethod_219(WrenVM* vm) { goForeignMethodCallback(vm, 219); }
void wrengoForeignMethod_220(WrenVM* vm) { goForeignMethodCallback(vm, 220); }
void wrengoForeignMethod_221(WrenVM* vm) { goForeignMethodCallback(vm, 221); }
void wrengoForeignMethod_222(WrenVM* vm) { goForeignMethodCallback(vm, 222); }
void wrengoForeignMethod_223(WrenVM* vm) { goForeignMethodCallback(vm, 223); }
void wrengoForeignMethod_224(WrenVM* vm) { goForeignMethodCallback(vm, 224); }
void wrengoForeignMethod_225(WrenVM* vm) { goForeignMethodCallback(vm, 225); }
void wrengoForeignMethod_226(WrenVM* vm) { goForeignMethodCallback(vm, 226); }
void wrengoForeignMethod_227(WrenVM* vm) { goForeignMethodCallback(vm, 227); }
void wrengoForeignMethod_228(WrenVM* vm) { goForeignMethodCallback(vm, 228); }
void wrengoForeignMethod_229(WrenVM* vm) { goForeignMethodCallback(vm, 229); }
void wrengoForeignMethod_230(WrenVM* vm) { goForeignMethodCallback(vm, 230); }
void wrengoForeignMethod_231(WrenVM* vm) { goForeignMethodCallback(vm, 231); }
void wrengoForeignMethod_232(WrenVM* vm) { goForeignMethodCallback(vm, 232); }
void wrengoForeignMethod_233(WrenVM* vm) { goForeignMethodCallback(vm, 233); }
void wrengoForeignMethod_234(WrenVM* vm) { goForeignMethodCallback(vm, 234); }
void wrengoForeignMethod_235(WrenVM* vm) { goForeignMethodCallback(vm, 235); }
void wrengoForeignMethod_236(WrenVM* vm) { goForeignMethodCallback(vm, 236); }
void wrengoForeignMethod_237(WrenVM* vm) { goForeignMethodCallback(vm, 237); }
void wrengoForeignMethod_238(WrenVM* vm) { goForeignMethodCallback(vm, 238); }
void wrengoForeignMethod_239(WrenVM* vm) { goForeignMethodCallback(vm, 239); }
void wrengoForeignMethod_240(WrenVM* vm) { goForeignMethodCallback(vm, 240); }
void wrengoForeignMethod_241(WrenVM* vm) { goForeignMethodCallback(vm, 241); }
void wrengoForeignMethod_242(WrenVM* vm) { goForeignMethodCallback(vm, 242); }
void wrengoForeignMethod_243(WrenVM* vm) { goForeignMethodCallback(vm, 243); }
void wrengoForeignMethod_244(WrenVM* vm) { goForeignMethodCallback(vm, 244); }
void wrengoForeignMethod_245(WrenVM* vm) { goForeignMethodCallback(vm, 245); }
void wrengoForeignMethod_246(WrenVM* vm) { goForeignMethodCallback(vm, 246); }
void wrengoForeignMethod_247(WrenVM* vm) { goForeignMethodCallback(vm, 247); }
void wrengoForeignMethod_248(WrenVM* vm) { goForeignMethodCallback(vm, 248); }
void wrengoForeignMethod_249(WrenVM* vm) { goForeignMethodCallback(vm, 249); }
void wrengoForeignMethod_250(WrenVM* vm) { goForeignMethodCallback(vm, 250); }
void wrengoForeignMethod_251(WrenVM* vm) { goForeignMethodCallback(vm, 251); }
void wrengoForeignMethod_252(WrenVM* vm) { goForeignMethodCallback(vm, 252); }
void wrengoForeignMethod_253(WrenVM* vm) { goForeignMethodCallback(vm, 253); }
void wrengoForeignMethod_254(WrenVM* vm) { goForeignMethodCallback(vm, 254); }
void wrengoForeignMethod_255(WrenVM* vm) { goForeignMethodCallback(vm, 255); }
void wrengoForeignMethod_256(WrenVM* vm) { goForeignMethodCallback(vm, 256); }
void wrengoForeignMethod_257(WrenVM* vm) { goForeignMethodCallback(vm, 257); }
void wrengoForeignMethod_258(WrenVM* vm) { goForeignMethodCallback(vm, 258); }
void wrengoForeignMethod_259(WrenVM* vm) { goForeignMethodCallback(vm, 259); }
void wrengoForeignMethod_260(WrenVM* vm) { goForeignMethodCallback(vm, 260); }
void wrengoForeignMethod_261(WrenVM* vm) { goForeignMethodCallback(vm, 261); }
void wrengoForeignMethod_262(WrenVM* vm) { goForeignMethodCallback(vm, 262); }
void wrengoForeignMethod_263(WrenVM* vm) { goForeignMethodCallback(vm, 263); }
void wrengoForeignMethod_264(WrenVM* vm) { goForeignMethodCallback(vm, 264); }
void wrengoForeignMethod_265(WrenVM* vm) { goForeignMethodCallback(vm, 265); }
void wrengoForeignMethod_266(WrenVM* vm) { goForeignMethodCallback(vm, 266); }
void wrengoForeignMethod_267(WrenVM* vm) { goForeignMethodCallback(vm, 267); }
void wrengoForeignMethod_268(WrenVM* vm) { goForeignMethodCallback(vm, 268); }
void wrengoForeignMethod_269(WrenVM* vm) { goForeignMethodCallback(vm, 269); }
void wrengoForeignMethod_270(WrenVM* vm) { goForeignMethodCallback(vm, 270); }
void wrengoForeignMethod_271(WrenVM* vm) { goForeignMethodCallback(vm, 271); }
void wrengoForeignMethod_272(WrenVM* vm) { goForeignMethodCallback(vm, 272); }
void wrengoForeignMethod_273(WrenVM* vm) { goForeignMethodCallback(vm, 273); }
void wrengoForeignMethod_274(WrenVM* vm) { goForeignMethodCallback(vm, 274); }
void wrengoForeignMethod_275(WrenVM* vm) { goForeignMethodCallback(vm, 275); }
void wrengoForeignMethod_276(WrenVM* vm) { goForeignMethodCallback(vm, 276); }
void wrengoForeignMethod_277(WrenVM* vm) { goForeignMethodCallback(vm, 277); }
void wrengoForeignMethod_278(WrenVM* vm) { goForeignMethodCallback(vm, 278); }
void wrengoForeignMethod_279(WrenVM* vm) { goForeignMethodCallback(vm, 279); }
void wrengoForeignMethod_280(WrenVM* vm) { goForeignMethodCallback(vm, 280); }
void wrengoForeignMethod_281(WrenVM* vm) { goForeignMethodCallback(vm, 281); }
void wrengoForeignMethod_282(WrenVM* vm) { goForeignMethodCallback(vm, 282); }
void wrengoForeignMethod_283(WrenVM* vm) { goForeignMethodCallback(vm, 283); }
void wrengoForeignMethod_284(WrenVM* vm) { goForeignMethodCallback(vm, 284); }
void wrengoForeignMethod_285(WrenVM* vm) { goForeignMethodCallback(vm, 285); }
void wrengoForeignMethod_286(WrenVM* vm) { goForeignMethodCallback(vm, 286); }
void wrengoForeignMethod_287(WrenVM* vm) { goForeignMethodCallback(vm, 287); }
void wrengoForeignMethod_288(WrenVM* vm) { goForeignMethodCallback(vm, 288); }
void wrengoForeignMethod_289(WrenVM* vm) { goForeignMethodCallback(vm, 289); }
void wrengoForeignMethod_290(WrenVM* vm) { goForeignMethodCallback(vm, 290); }
void wrengoForeignMethod_291(WrenVM* vm) { goForeignMethodCallback(vm, 291); }
void wrengoForeignMethod_292(WrenVM* vm) { goForeignMethodCallback(vm, 292); }
void wrengoForeignMethod_293(WrenVM* vm) { goForeignMethodCallback(vm, 293); }
void wrengoForeignMethod_294(WrenVM* vm) { goForeignMethodCallback(vm, 294); }
void wrengoForeignMethod_295(WrenVM* vm) { goForeignMethodCallback(vm, 295); }
void wrengoForeignMethod_296(WrenVM* vm) { goForeignMethodCallback(vm, 296); }
void wrengoForeignMethod_297(WrenVM* vm) { goForeignMethodCallback(vm, 297); }
void wrengoForeignMethod_298(WrenVM* vm) { goForeignMethodCallback(vm, 298); }
void wrengoForeignMethod_299(WrenVM* vm) { goForeignMethodCallback(vm, 299); }
